version: "2.1"

services:
  server:
    image: softwarecraftsmen/atlassian-plugin-sdk-confluence:${ATLASSIAN_PLUGIN_SDK_TAG}
    build: ./
    ports:
      - ${CONFLUENCE_HTTP_PORT}:1990
    volumes:
      - ${PLUGIN_PROJECT_DIR}:/project
      - dot_m2:/root/.m2

    working_dir: /project
    stop_grace_period: 1m0s
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://server:1990/confluence"]
#      interval: 60s
#      timeout: 10s
#      retries: 6
    #network_mode: host
    hostname: confluence

volumes:
  dot_m2:
    external: true

